---
title       : Finance Advanced
subtitle    : college 1
author      : Witek ten Hove
job         : Instructor HAN University of AS
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## 1. Toekomstige waarde
$TW = CW * (1 + R)^{t}$   

<iframe width='100%' height='600' src='http://ec2-54-76-89-164.eu-west-1.compute.amazonaws.com:3838/FinAdv/Coll1/FV/' frameborder='0'></iframe>

---

## 1.2 Toekomstige waarde
1. Neem een vermogen (CW) = 10.000 EUR en een rentevoet (R) = 6%. Na hoeveel jaar is het vermogen ongeveer verdubbeld?
2. Hetzelfde met CW = 10.000 EUR en R = 9%.
3. Welk patroon kun je ontdekken?

<iframe width='100%' height='600' src='http://ec2-54-76-89-164.eu-west-1.compute.amazonaws.com:3838/FinAdv/Coll1/FV/' frameborder='0'></iframe>

---
## 2. Contante waarde

$CW = \dfrac{TW}{(1 + R)^{t}}$

```{r nvd3plot, results = 'asis', comment = NA, message = F, echo = F, cache=FALSE}
require(rCharts)
CFs <- 1000
DiscR <- 0.05
Time <- 300

PV <- sapply(c(1:Time), function(x) CFs*(1+DiscR)^(-1*x))
TotPV <- sum(PV)
PVs <- data.frame(Time = c(1:Time),PV)

h1 <- rCharts::Highcharts$new()
h1$chart(type='line')
h1$series(data = PVs$PV, marker= list(symbol = 'circle'))
h1$series(data = PVs$PV, marker= list(symbol = 'circle'))
# h1 <- hPlot(x = 'Time', y = 'PV', data = PVs, type = 'line')
h1$title(text = paste0('Verloop contante waarde in tijd met C = ', CFs, ' en R = ', DiscR*100, '%'))
h1$tooltip(formatter = "#! function(){return('<b>t: </b>' + this.x + '<br/>' + '<b>PV: </b>' + this.y);} !#")
h1$colors(c('rgb(255,85,0)', 'rgb(255,85,0)'))
h1$legend(enabled = FALSE)
h1$xAxis(categories = PVs$Time, tickInterval = 50, title = list(text = 'Tijd'))
h1$yAxis(title = list(text = 'Contante Waarde'))
h1$addParams(width = 1000, height = 1000, dom = 'chart1')
h1$show('inline')
```

---

## 3. Contante waarde gelijke reeks

$CW = \displaystyle\sum\limits_{i=1}^{300}\dfrac{C}{(1 + R)^{i}}$

1. Verander de waarde van R een aantal maal. Welk patroon kun je herkennen?

<iframe width='100%' height='600' src='http://ec2-54-76-89-164.eu-west-1.compute.amazonaws.com:3838/FinAdv/Coll1/AnnPV/' frameborder='0'></iframe>


---

## 4. Aflossingsschema annuiteit
$CW = Ann * \dfrac{1-\dfrac{1}{(1 + R)^{t}}}{R}$

<iframe width='100%' height='600' src='http://ec2-54-76-89-164.eu-west-1.compute.amazonaws.com:3838/FinAdv/Coll1/AnnTbl/' frameborder='0'></iframe>

---

## 5. Contante waarde ongelijke reeks

$\displaystyle\sum\limits_{i=1}^{T}\dfrac{C_i}{(1 + R)^{i}}$   

<iframe width='100%' height='600' src='http://ec2-54-76-89-164.eu-west-1.compute.amazonaws.com:3838/FinAdv/Coll1/CashPV/' frameborder='0'></iframe>


---

## 6. Netto contante waarde (NCW)
$NCW = -I + \displaystyle\sum\limits_{i=1}^{T}\dfrac{C_i}{(1 + R)^{i}}$

<iframe width='100%' height='600' src='http://ec2-54-76-89-164.eu-west-1.compute.amazonaws.com:3838/FinAdv/Coll1/NPV/' frameborder='0'></iframe>


---

## 6.1 Netto contante waarde (NCW)

1. Neem I = 10000, C = 1500 en een looptijd van 10 periodes. Bij welke disconteringsvoet is de NCW ongeveer nul?
2. Bepaal m.b.v. het schema op slide 5 de IRR van de onder 1 genoemde investering.

<iframe width='100%' height='600' src='http://ec2-54-76-89-164.eu-west-1.compute.amazonaws.com:3838/FinAdv/Coll1/NPV/' frameborder='0'></iframe>


---


## Ter afsluiting
   
    
### ~ If only God would give me some clear sign!
### Like making a large deposit in my name at a Swiss Bank ~

- Woody Allen

