---
title: "Analyse CFA WK1"
author: "Witek ten Hove"
date: "Zaterdag, 13 September 2014"
output: pdf_document
---


```{r, , echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
source("RekentoetsAnalyse.R")
```

In totaal hebben `r stdCntW` studenten deelgenomen aan de colleges of in ieder geval aan de rekentoets tijdens de colleges.
```{r echo=FALSE, results='asis', comment=FALSE, warning=FALSE, message=FALSE, cache=FALSE, cache.comments=FALSE}
    
             print(xtblKlW, comment=FALSE, include.rownames=FALSE, floating = TRUE)

```



```{r echo=FALSE, results='asis', comment=FALSE, warning=FALSE, message=FALSE, cache=FALSE, cache.comments=FALSE}
    
             print(xtblOplKlW, comment=FALSE, floating = TRUE)

```



```{r echo=FALSE, results='asis', comment=FALSE, warning=FALSE, message=FALSE, cache=FALSE, cache.comments=FALSE}
    
             print(xtblKlBGAW, comment=FALSE, floating = TRUE)

```


```{r echo=FALSE, results='asis', comment=FALSE, warning=FALSE, message=FALSE, cache=FALSE, cache.comments=FALSE}
    
             hist(round(WK1New$Score[WK1New$Klas == "N-C02"|WK1New$Klas == "N-C03"]/10,0)*10,
                  col = "Red",
                  main = "Verdeling Scores Rekentoets",
                  xlab = "Score min/max",
                  ylab = "Aantal",
                  labels = TRUE,
                  ylim = c(0, 20),
                  right = FALSE)

               
```